### ISSUE TITLE
Proposal to enlarge the number of connections into 10000, 20000, 40000, 60000

### ISSUE THREAD

**Issue by xfeep** [ptaoussanis/clojure-web-server-benchmarks#21]
Hi,

I have done some updates 

1. auto downloading before startup & more simpler configurations of nginx-clojure
2. enlarge the number of connections into 10000, 20000, 40000, 60000
3. use [wrk2](https://github.com/giltene/wrk2) instead of wrk to get more accurate results
4. add somethings about linux tuning in scripts/tune_linux.sh
5. commit the new results including serveral charts **but have not** updated the index file (README.md) yet

@ptaoussanis @ztellman @shenfeng @jcrossley3 Would somebody  give us any sugguestions ? 

There are some links and charts

1. [stripped result which is shorter and more readable](https://github.com/ptaoussanis/clojure-web-server-benchmarks/blob/master/results/20150114-05-05.stripped)
2. [raw result](https://github.com/ptaoussanis/clojure-web-server-benchmarks/blob/master/results/20150114-05-05)
3. serveral charts

![RPS](https://raw.githubusercontent.com/ptaoussanis/clojure-web-server-benchmarks/wrk2/results/20150114-05-05-rps.png)

![Error Rate](https://raw.githubusercontent.com/ptaoussanis/clojure-web-server-benchmarks/wrk2/results/20150114-05-05-ers.png)

![99% Latency](https://raw.githubusercontent.com/ptaoussanis/clojure-web-server-benchmarks/wrk2/results/20150114-05-05-lat99.png)

BTW @jcrossley3 to let  immutant 1 work I have to add this line in the immutant/.install/releases/immutant-1.1.4-slim/jboss/standalone/configuration/standalone.xml

```xml
    <system-properties>
        ..................
        <property name='org.immutant.web.http.maxThreads' value='2048'/>
    </system-properties>
```

and increase the jvm memory in standalone.conf

```shell
if [ "x$JAVA_OPTS" = "x" ]; then
   JAVA_OPTS="-Xms3g -Xmx3g -XX:MaxPermSize=256m -Djava.net.preferIPv4Stack=true"
   JAVA_OPTS="$JAVA_OPTS -Djboss.modules.system.pkgs=$JBOSS_MODULES_SYSTEM_PKGS -Djava.awt.headless=true"
```

**Comment by xfeep** [comment]
I prefer to use wrk2 instead of wrk because when we use wrk

1. the latency results  fluctuate wildly e.g. from 300ms to 30s even with the same test to the same server
2. for some java server connections issued by wrk never reach 40000  , e.g. the result of `netstat -anp | grep $PORT` less than 80000
3. the results of most of tested servers have a large amount of timeout errors

**Comment by ztellman** [comment]
While I'm glad that Aleph and nginx-clojure can apparently scale to this number of connections, I don't think this is particularly representative of a typical workload.  I have no objections to using wrk2, and no objection to expanding the range of connections we test, but I think we should continue to benchmark 32 - 1024 connections.

**Comment by xfeep** [comment]
Maybe we can keep two groups of benchmarks.
One for small number of connections and the other for large number of
connections.
Different group can use different configurations (e.g. memory, threads , gc
policy etc.) and shell scripts.
Because modern browsers at most have the 6-8  concurrent http keepalive
connections per domain. (see
http://sgdev-blog.blogspot.com/2014/01/maximum-concurrent-connection-to-same.html
).
So about the small number of connections group I think the start of range
should be 8*16 = 128 at least.
BTW Do we need non-keepalive benchmark too?
Only non-keepalive benchmark can measure the efficiency of creation &
closing connections.

**Comment by ztellman** [comment]
If we can come up with a way to present all the data, I think it's great to have a wider range of benchmarks.  I will say, though, that even if modern browsers open up multiple connections, you're not going to see a uniform distribution of request volume across all these connections, which is what this benchmark is measuring.  Also, these connections aren't going to be terminated at your web server, they're going to be at an upstream load balancer, which will keep a significantly smaller number of connections open to the servers behind it, because most of the connections are 99+% idle.

In short, I care a lot more if Amazon's ELB, or HAProxy, etc can handle lots of concurrent connections and open new connections quickly. For example, at Factual we have a service that sits behind ELB and processes 200k+ qps across 4 instances.  The request patterns for these servers is **very similar** to the existing benchmarks, because ELB opens up persistent connections to my machines, and funnels large volumes of requests across them.

I expect this will be true of most, if not all, high-volume web services.  You'll need more than one server for redundancy and scaling, so you can always put something upstream and treat "low volume of requests over lots of connections" as "high volume of requests over a few connections", which is *way* easier operationally.

The only use-case where this isn't true is [Urban Airship](http://urbanairship.com/blog/2010/08/24/c500k-in-action-at-urban-airship/) style services, but that's not an HTTP service, it's a carefully engineered TCP service that avoids any sorts of wrappers on top of the raw network primitives.  Please let me know if there's something I'm overlooking, but I think the benchmarks you're proposing are just less relevant than the ones we already have.

**Comment by jcrossley3** [comment]
WRT the Immutant 1 errors, I intend to remove Immutant 1 from the benchmarks once 2.0.Final is released anyway.

**Comment by xfeep** [comment]
@ztellman 
Thanks for your detail explanation!

Reserve proxy such as HAProxy, ELB ,Nginx etc are widly used by high PVs sites but there are really some reasons about also including non-keepAlive benchmarks and large number of connections

1. Efficient management of connections  is HTTP Servers‘ own work regardless deployment and this work includes creation and closing connectons.
2. HTTP (TCP layer 7) reserve proxy is not no cost. Amazon's ELB has its own price. Although the softwares of HAProxy , Nginx are free but they cost more cpu usages and maybe even more computers. And to get the real ip we need modify our existing code, it is painful sometimes. So sometimes we use TCP layer 4 reserve proxy , e.g. use TCP mode HAProxy (not HTTP mode) , LVS , F5 etc. TCP 's keepAlive is just a different thing from HTTP's keepAlive. Of course we maybe use both of TCP layer 4 & 7 reserve proxy , e.g LVS + HAProxy but it is out of the scope of this issue.
3. Non-keepAlive benchmarks will help us to determine when and whether we need HTTP reserve proxy for performance.
4. Even we use HTTP reserve proxy such as HAProxy, ELB or Nginx, concurrent connections to the backend still can not be reduced for some cases , e.g. when  long polling / Server Sent Events are used for near realtime sub/pub.

**Comment by ztellman** [comment]
I agree, there are situations that fall outside what I described, and that benchmarks that measure large numbers of connections or non-keepalive requests are useful.  I strongly disagree that they should replace the existing benchmarks, which I believe are much more relevant for 99+% of people using Clojure webservers.

I also think that if we're going to have such a wide array of benchmarks, graphs, etc. we need to spend some time discussing how it will be presented, what sort of explanatory documentation we provide to make it clear.  Just adding more bar graphs would be needlessly confusing.

**Comment by xfeep** [comment]
I agree we should not replace the existing benchmarks. So I think we can arrange benchmarks as this layout (two groups)

1. 32~1024 connections
     + keepAlive on 
       * throughput graph (queries per second ? )
       * errors graph (errors_num / (errors_num + success_num) )
       * mean latency 
       * 99% latency (or 99.99% latency ?)
     + keepAlive off
       * throughput graph (queries per second ? )
       * errors graph (errors_num / (errors_num + success_num) )
       * mean latency 
       * 99% latency (or 99.99% latency ?)
2. 10000 ~ 60000 connections
     + keepAlive on 
       * throughput graph (queries per second ? )
       * errors graph (errors_num / (errors_num + success_num) )
       * mean latency 
       * 99% latency (or 99.99% latency ?)  

Please give more suggestions!

**Comment by xfeep** [comment]
Hello , I have done 

1. scripts for benchmarks 
    * 32~1024 connections + keepAlive on
    * 32~1024 connections + keepAlive off, 
    * 10000 ~ 60000 connections +  keepAlive on
2. wrk2 stripped results parser which can be used to generate
    * text table about benchmarks
    * charts about throughput, errors, mean latency, 99% latency
3. the latest benchmarks

+ 32~1024 connections
     + keepAlive on [(text table)](https://raw.githubusercontent.com/ptaoussanis/clojure-web-server-benchmarks/master/results/20150129-01-40-table.txt) 
       * [throughput chart](https://raw.githubusercontent.com/ptaoussanis/clojure-web-server-benchmarks/master/results/20150129-01-40-qps.png)
       * [errors chart](https://raw.githubusercontent.com/ptaoussanis/clojure-web-server-benchmarks/master/results/20150129-01-40-errs.png)
       * [mean latency chart](https://raw.githubusercontent.com/ptaoussanis/clojure-web-server-benchmarks/master/results/20150129-01-40-mlat.png) 
       * [99.99% latency chart](https://raw.githubusercontent.com/ptaoussanis/clojure-web-server-benchmarks/master/results/20150129-01-40-n4lat.png)
     + keepAlive off  [(text table)](https://raw.githubusercontent.com/ptaoussanis/clojure-web-server-benchmarks/master/results/20150129-03-55-nonkeepalive-table.txt)
       * [throughput chart](https://raw.githubusercontent.com/ptaoussanis/clojure-web-server-benchmarks/master/results/20150129-03-55-nonkeepalive-qps.png)
       * [errors chart](https://raw.githubusercontent.com/ptaoussanis/clojure-web-server-benchmarks/master/results/20150129-03-55-nonkeepalive-errs.png)
       * [mean latency chart](https://raw.githubusercontent.com/ptaoussanis/clojure-web-server-benchmarks/master/results/20150129-03-55-nonkeepalive-mlat.png) 
       * [99.99% latency chart](https://raw.githubusercontent.com/ptaoussanis/clojure-web-server-benchmarks/master/results/20150129-03-55-nonkeepalive-n4lat.png)
+ 10000 ~ 60000 connections
     + keepAlive on [ (text table)](https://raw.githubusercontent.com/ptaoussanis/clojure-web-server-benchmarks/master/results/20150129-06-24-largeNumofConns-table.txt) 
       * [throughput chart](https://raw.githubusercontent.com/ptaoussanis/clojure-web-server-benchmarks/master/results/20150129-06-24-largeNumofConns-qps.png)
       * [errors chart](https://raw.githubusercontent.com/ptaoussanis/clojure-web-server-benchmarks/master/results/20150129-06-24-largeNumofConns-errs.png)
       * [mean latency chart](https://raw.githubusercontent.com/ptaoussanis/clojure-web-server-benchmarks/master/results/20150129-06-24-largeNumofConns-mlat.png) 
       * [99.99% latency chart](https://raw.githubusercontent.com/ptaoussanis/clojure-web-server-benchmarks/master/results/20150129-06-24-largeNumofConns-n4lat.png)

If there's no problem and objection I 'll prepare to update README.md to add the latest results and close this issue.
**Thanks in advance for any suggestions and ideas!**

**Comment by ptaoussanis** [comment]
@xfeep Thanks a lot for this Zhang. I'm just travelling atm - I will try look over this and get back to you in the next couple days if that's okay?

If no one else has any objections, could you please make this a PR to a development branch (not `master`)? I'd like to play with a few ways of starting to group/organize all the benchmarks that we're accumulating, but that'll be easier once I have all the results in front of me.

Cheers! :-)

**Comment by xfeep** [comment]
@ptaoussanis thanks for your reply. no problem to make this a PR to a development branch (not master).

**Comment by xfeep** [comment]
@ptaoussanis I have removed all previous commits about 
+ wrk2
+ non-keepalive benchmark
+ 10000~60000 connections benchmark 

from the master branch to the new branch [wrk2](https://github.com/ptaoussanis/clojure-web-server-benchmarks/tree/wrk2).

I have also update the README.md in the new branch `wrk2`  and create a pull request #23 .

**Comment by ptaoussanis** [comment]
Closing this issue, will continue the discussion with PR #23.
