### ISSUE TITLE
Adjust new graph utils to generate sorted graphs

### ISSUE THREAD

**Issue by ptaoussanis** [ptaoussanis/clojure-web-server-benchmarks#26]
I.e. sort entries by highest->lowest value [like this](https://github.com/ptaoussanis/clojure-web-server-benchmarks/blob/master/results/legacy/20141106-13-28.png) instead of [like this](https://github.com/ptaoussanis/clojure-web-server-benchmarks/blob/master/results/1k-keepalive/20150217-16-34-qps.png)

**Comment by xfeep** [comment]
@ptaoussanis  Hi Taoussanis, maybe use line chart is better than sorted histogram chart in this case because we can not determine which entry to be as sort-by field.
e.g. in throughput chart only sort by the result of 1024 conns, or 60000 conns connections  is maybe arbitrary.

**Comment by ztellman** [comment]
I just sorted by the throughput on the highest number of connections, it seemed to work well enough.

As an unrelated note, the latency graphs seem to suggest that the unit of time is seconds, but I suspect it's actually milliseconds.  If so, can you update the titles to reflect this?

**Comment by xfeep** [comment]
@ztellman The unit of time in the latency graphs is really seconds. Because wrk2 use a constant stress requests per second, so the latency time is higher than results from wrk. 

BTW We use these code to parse and format latency time

```clojure
(defn format-time [t]
  (if (nil? t)
    0
    (let [[_ num unit] (re-find #"(\d+[\.]\d+)([^\d\.]*)" t)
          num (Float/parseFloat num)]
      (case unit
        "us" (/ num 1000000)
        "ms" (/ num 1000)
        "m"  (* num 60)
        num))))
```

**Comment by ptaoussanis** [comment]
Hi Zhang, sorry for the delay replying - have been travelling. Yeah, I'm in agreement with Zach about just sorting high->low against the highest connection test.

So the 32->1k tests can sort by the 1k results, and the 10k->16k tests can sort by the 60k results.

Thanks!
